server:
  port: 3002
spring:
  application:
    name: price
  kafka:
    bootstrap-servers: 192.168.1.35:9092
    admin:
      bootstrap-servers: 192.168.1.35:9092
    producer:
      bootstrap-servers: 192.168.1.35:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: 192.168.1.35:9092
      group-id: quoteGroup
      auto-offset-rest: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'